# This is a basic workflow to help you get started with Actions

name: trigger-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Export cluster.conf
        id: export-cluster-conf
        run: |
          cluster_conf_encoded="$(cat cluster.conf | base64 -w 0)"
          echo $cluster_conf_encoded
          echo "cluster_conf_encoded="$cluster_conf_encoded"" >> $GITHUB_ENV
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: alembiewski/gha-test-dep
          event-type: my-event
          client-payload: '{ "cluster_conf_encoded": "${{  env.cluster_conf_encoded }}"}'
